# Generated by Django 6.0.4 on 2026-05-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0)),
                ('popularity', models.FloatField(default=0)),
                ('genres', models.ManyToManyField(to='movies.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.language')),
            ],
            options={
                'indexes': [models.Index(fields=['language', 'popularity'], name='movies_movi_languag_b01933_idx'), models.Index(fields=['popularity'], name='movies_movi_popular_114287_idx')],
            },
        ),
    ]
