# Generated by Django 6.0.4 on 2026-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_languag_b01933_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_popular_114287_idx',
        ),
        migrations.AddField(
            model_name='movie',
            name='languages',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi')], max_length=50, null=True),
        ),
    ]
